language: python
python:
- "2.7"
- "3.4"
- "3.5"
install:
- "pip install --upgrade pip setuptools"
- "python setup.py develop"

# Add demo site to the Python path separately to run the tests
- "export PYTHONPATH=$PYTHONPATH:$(pwd)/demosite"
script:
- "python setup.py test"
